name: Test on Push
run-name: Testing Git Action for calculator

on: [push]

jobs:
  trail-ubuntu-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List all files
        run: ls -l

    
    
        

