name: Test on Push
run-name: Testing Git Action for git push

on: [push]

jobs:
  trail-ubuntu-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List all files
        run: ls -l

      - name: printing the secrets
        run: |
            echo "${{ secrets.SECRET_KEYS }}"
            

    
        