name: Test on Pull
run-name: Testing Git Action for git pull

on: [push]

jobs:
  trail-ubuntu-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List all files
        run: ls -l
